use std::collections::HashSet;

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct AlgVariant {
    pub name: &'static str,
    pub value: u16,
    pub asym: bool,
    pub sym: bool,
    pub hash: bool,
    pub sign: bool,
    pub anon_sign: bool,
    pub enc: bool,
    pub meth: bool,
    pub obj: bool,
}

pub const ALGS: [AlgVariant; 39] = [
    AlgVariant {
        name: "Error",
        value: 0x0000,
        asym: false,
        sym: false,
        hash: false,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "RSA",
        value: 0x0001,
        asym: true,
        sym: false,
        hash: false,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: true,
    },
    AlgVariant {
        name: "TDES",
        value: 0x0003,
        asym: false,
        sym: true,
        hash: false,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "SHA1",
        value: 0x0004,
        asym: false,
        sym: false,
        hash: true,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "HMAC",
        value: 0x0005,
        asym: false,
        sym: false,
        hash: true,
        sign: true,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "AES",
        value: 0x0006,
        asym: false,
        sym: true,
        hash: false,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "MGF1",
        value: 0x0007,
        asym: false,
        sym: false,
        hash: true,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: true,
        obj: false,
    },
    AlgVariant {
        name: "KeyedHash",
        value: 0x0008,
        asym: false,
        sym: false,
        hash: true,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: true,
    },
    AlgVariant {
        name: "XOR",
        value: 0x000A,
        asym: false,
        sym: true,
        hash: true,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "SHA256",
        value: 0x000B,
        asym: false,
        sym: false,
        hash: true,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "SHA384",
        value: 0x000C,
        asym: false,
        sym: false,
        hash: true,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "SHA512",
        value: 0x000D,
        asym: false,
        sym: false,
        hash: true,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "Null",
        value: 0x0010,
        asym: true,
        sym: true,
        hash: true,
        sign: true,
        anon_sign: true,
        enc: true,
        meth: true,
        obj: true,
    },
    AlgVariant {
        name: "SM3_256",
        value: 0x0012,
        asym: false,
        sym: false,
        hash: true,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "SM4",
        value: 0x0013,
        asym: false,
        sym: true,
        hash: false,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "RSASSA",
        value: 0x0014,
        asym: true,
        sym: false,
        hash: false,
        sign: true,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "RSAES",
        value: 0x0015,
        asym: true,
        sym: false,
        hash: false,
        sign: false,
        anon_sign: false,
        enc: true,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "RSAPSS",
        value: 0x0016,
        asym: true,
        sym: false,
        hash: false,
        sign: true,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "OAEP",
        value: 0x0017,
        asym: true,
        sym: false,
        hash: true,
        sign: false,
        anon_sign: false,
        enc: true,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "ECDSA",
        value: 0x0018,
        asym: true,
        sym: false,
        hash: false,
        sign: true,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "ECDH",
        value: 0x0019,
        asym: true,
        sym: false,
        hash: false,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: true,
        obj: false,
    },
    AlgVariant {
        name: "ECDAA",
        value: 0x001A,
        asym: true,
        sym: false,
        hash: false,
        sign: true,
        anon_sign: true,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "SM2",
        value: 0x001B,
        asym: true,
        sym: false,
        hash: false,
        sign: true,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "ECSCHNORR",
        value: 0x001C,
        asym: true,
        sym: false,
        hash: false,
        sign: true,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "ECMQV",
        value: 0x001D,
        asym: true,
        sym: false,
        hash: false,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: true,
        obj: false,
    },
    AlgVariant {
        name: "Kdf1Sp800_56a",
        value: 0x0020,
        asym: false,
        sym: false,
        hash: true,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: true,
        obj: false,
    },
    AlgVariant {
        name: "KDF2",
        value: 0x0021,
        asym: false,
        sym: false,
        hash: true,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: true,
        obj: false,
    },
    AlgVariant {
        name: "Kdf1Sp800_108",
        value: 0x0022,
        asym: false,
        sym: false,
        hash: true,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: true,
        obj: false,
    },
    AlgVariant {
        name: "ECC",
        value: 0x0023,
        asym: true,
        sym: false,
        hash: false,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: true,
    },
    AlgVariant {
        name: "SYMCIPHER",
        value: 0x0025,
        asym: false,
        sym: true,
        hash: false,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: true,
    },
    AlgVariant {
        name: "CAMELLIA",
        value: 0x0026,
        asym: false,
        sym: true,
        hash: false,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "SHA3_256",
        value: 0x0027,
        asym: false,
        sym: false,
        hash: true,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "SHA3_384",
        value: 0x0028,
        asym: false,
        sym: false,
        hash: true,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "SHA3_512",
        value: 0x0029,
        asym: false,
        sym: false,
        hash: true,
        sign: false,
        anon_sign: false,
        enc: false,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "CTR",
        value: 0x0040,
        asym: false,
        sym: true,
        hash: false,
        sign: false,
        anon_sign: false,
        enc: true,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "OFB",
        value: 0x0041,
        asym: false,
        sym: true,
        hash: false,
        sign: false,
        anon_sign: false,
        enc: true,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "CBC",
        value: 0x0042,
        asym: false,
        sym: true,
        hash: false,
        sign: false,
        anon_sign: false,
        enc: true,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "CFB",
        value: 0x0043,
        asym: false,
        sym: true,
        hash: false,
        sign: false,
        anon_sign: false,
        enc: true,
        meth: false,
        obj: false,
    },
    AlgVariant {
        name: "ECB",
        value: 0x0044,
        asym: false,
        sym: true,
        hash: false,
        sign: false,
        anon_sign: false,
        enc: true,
        meth: false,
        obj: false,
    },
];

impl AlgVariant {
    pub fn is_type(&self, name: &str) -> bool {
        match name {
            "asym" => self.asym,
            "sym" => self.sym,
            "hash" => self.hash,
            "sign" => self.sign,
            "anon_sign" => self.anon_sign,
            "enc" => self.enc,
            "meth" => self.meth,
            "obj" => self.obj,
            _ => panic!(),
        }
    }

    pub fn types(&self) -> HashSet<String> {
        let r = [
            "asym",
            "sym",
            "hash",
            "sign",
            "anon_sign",
            "enc",
            "meth",
            "obj",
        ]
        .iter()
        .filter_map(|t| match self.is_type(t) {
            true => Some(t.to_string()),
            false => None,
        })
        .collect();

        r
    }
}
